services:
  netflix-bot:
    build: .
    container_name: netflix-bot
    restart: always
    env_file:
      - .env
    environment:
      - PORT=8080
      - DATA_DIR=/data
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
